INSERT INTO `items` (label, name) VALUES 
	('Semilla de Cocaina','cocaseed'),
	('Planta de Cocaina','cocaplant'),
	('Cocaina sin pastillas','cocawithout'),
	('Pastillas','pastillas'),
	('Cocaina','coca'),
	('Pala','shovel'),
	('Marihuana','weed'),
	('Marihuana Embolsada','weed_pooch'),
	('Piezas de Armas','weapon_shit'),
	('Nevaditos','nevadito'),
	('Cañon de Armas','canion'),
	('Llaves de Esposas','keys'),
	('Esposas','grilletes'),
	('Culatas de Armas','culett'),
	('Mirillas de Armas','scope'),
	('Metalina','metalina'),
	('Opio','opio'),
	('Opio sin Metalina','opiowithout'),
	('Semillas de Opio','opioseed'),
	('Planta de Opio','opioplant'),
	('Carton','carton'),
	('LSD','lsd'),
	('LSD Embolsado','lsd_pooch'),
	('Crack','crack')
;